# BungeePortals configuration file, visit www.spigotmc.org/resources/bungeeportals.19 for help.
NoPortalPermissionMessage: '&cYou do not have permission to go to the server {destination}.'
CooldownMessage: '&cPlease wait &a{time} &cseconds until attempting to teleport again.'
CooldownSeconds: 5
AuthMeHook: true
