name: BungeePortals
version: ${project.version}
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: YoFuzzy3
main: net.yofuzzy3.bungeeportals.BungeePortals
url: http://www.spigotmc.org/resources/bungeeportals.19/
softdepend: [WorldEdit, AuthMe]

commands:
    bportals:
        description: Main BPortals command.
        aliases: [bp, bportal]
        permission: bungeeportals.command.bportals

permissions:
    bungeeportals.command.bportals:
        description: Allowed to access the command /BPortals.
        default: op
    bungeeportals.portal.*:
        description: Access to all portals.
        default: false
